# Training configuration
GPU: [0]

VERBOSE: False

MODEL:
  MODE: 'CF-UFormer_LSRW'

# Optimization arguments.
OPTIM:
  BATCH: 6
  EPOCHS: 500
  # EPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 128
  VAL_PS: 128
  TRAIN_DIR: './datasets/LSRW/train'     # path to training data
  VAL_DIR: './datasets/LSRW/test'       # path to validation data
  SAVE_DIR: './checkpoints'           # path to save models and images
